### ISSUE TITLE
No repository for "ClientEntity" was found. Looks like this entity is not registered in current "default" connection?

### ISSUE THREAD

**Issue by adamgajzlerowicz** [switchit-conseil/nestjs-oauth2-server-module#10]
I am trying to use the module. 
I don't think documentation is right btw. It specifies to import `OAuth2Module`. This is not available (capitalization error). Importing `Oauth2Module` gives the following error:
```
No repository for "ClientEntity" was found. Looks like this entity is not registered in current "default" connection?
```

If you'd like to see the code, it's here:
https://github.com/adamgajzlerowicz/nest-learning/pull/1

Can I get some pointers, please?

**Comment by reaflower** [comment]
Add entity to TypeOrmModule when import ORM to app, like this:

`@Module({
  imports: [AuthModule, UsersModule,TypeOrmModule.forRoot({
    type:'mongodb',
    url:'mongodb://writer:password@localhost:27017/lb4',
    entities:[User,ClientEntity,AccessTokenEntity]
  }) 
}),],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}`
-----------
sr about code, i don't know how to add line break
